name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install modules
      run: npm ci --ignore-scripts
    - name: Run ESLint
      run: npx eslint ./src --ext .js,.jsx,.ts,.tsx